import { z } from 'zod';
import rawCopy from '../../content/site-copy.json';

const text = z.string().min(1);
export const siteCopySchema = z.object({
  brand: z.object({
    name: text,
    region: text,
    homeAriaLabel: text,
    descriptor: text,
    cartAriaLabel: text,
    headerNote: z.array(text).length(2),
    footerStatement: z.array(text).length(2),
    footerBase: text,
  }),
  navigation: z.object({
    primaryLabel: text,
    mobileLabel: text,
    exploreLabel: text,
    items: z.array(z.object({ href: z.string().startsWith('/'), label: text })).min(1),
    contactLabel: text,
    menuOpenLabel: text,
    menuCloseLabel: text,
    mobileFooterStatement: text,
    footerNavigation: z.array(z.object({ label: text, links: z.array(z.object({ href: z.string().startsWith('/'), label: text })).min(1) })).length(3),
  }),
  home: z.object({
    title: text,
    description: text,
    heroEyebrow: text,
    heroHeading: text,
    heroIntro: text,
    heroCta: text,
    heroAlt: text,
    heroCaption: text,
    heroNote: text,
    promiseLabel: text,
    promises: z.array(z.object({ title: text, copy: text })).length(4),
    manifestoEyebrow: text,
    manifestoHeading: text,
    manifestoParagraphs: z.array(text).length(2),
    collectionEyebrow: text,
    collectionHeading: z.array(text).length(2),
    collectionIntro: text,
    browseEyebrow: text,
    browseHeading: z.array(text).length(2),
    browseCta: text,
    processEyebrow: text,
    processHeading: text,
    processBody: text,
    processCta: text,
    processSteps: z.array(z.object({ title: text, copy: text })).length(3),
  }),
  catalogue: z.object({
    title: text,
    description: text,
    asideLabel: text,
    allLabel: text,
    softLaunchLabel: text,
    placeLabel: text,
    asideEyebrow: z.array(text).length(2),
    asideQuote: text,
    sealLines: z.array(text).length(3),
    heading: text,
    headingEyebrow: text,
    intro: text,
    searchLabel: text,
    searchPlaceholder: text,
    placeFilterLabel: text,
    allPlacesLabel: text,
    availabilityLabel: text,
    availabilityBadge: text,
    availabilityNote: text,
    sortLabel: text,
    newestLabel: text,
    titleSortLabel: text,
    collectionLabel: text,
    resultCountLabel: text,
    cardLink: text,
    emptyEyebrow: text,
    emptyHeading: text,
    resetLabel: text,
  }),
  cart: z.object({
    title: text,
    description: text,
    eyebrow: text,
    itemCount: text,
    heading: text,
    emptyTitle: text,
    emptyCopy: text,
    browseCta: text,
    sceneLabel: text,
    sceneAlt: text,
    sceneScript: text,
    sceneCopy: text,
  }),
  product: z.object({
    breadcrumbLabel: text,
    galleryLabel: text,
    openImageLabel: text,
    previousImageLabel: text,
    nextImageLabel: text,
    chooseGalleryImageLabel: text,
    showImageLabel: text,
    placeSuffix: text,
    sizeLabel: text,
    framingLabel: text,
    printOnlyLabel: text,
    frameStyleLabel: text,
    selectionSuffix: text,
    noStockLabel: text,
    commerceEyebrow: text,
    commerceTitle: text,
    commerceCopy: text,
    shareGroupLabel: text,
    shareLabel: text,
    copyLinkLabel: text,
    linkCopiedMessage: text,
    shareOpenedMessage: text,
    printSizesLabel: text,
    printSizesValue: text,
    presentationLabel: text,
    presentationValue: text,
    orderingLabel: text,
    orderingValue: text,
    deliveryLabel: text,
    returnsLabel: text,
    lightboxLabel: text,
  }),
});

export const siteCopy = siteCopySchema.parse(rawCopy);
